- name: Labeler
  uses: actions/labeler@v5.0.0
  with:
    # The GitHub token used to manage labels
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    # The path for the label configurations
    configuration-path: .github/labeler.yml
    # Whether or not to remove labels when matching files are reverted
    sync-labels: true
    # Whether or not to auto-include paths starting with dot (e.g. `.github`)
    dot: true
    # The pull request number(s)
    pr-number: ${{ github.event.pull_request.number }}
