name: "Labeler and Scheduled Labeling"
on:
  push:
    paths:
      - '.github/labeler.yml'
  schedule:
    - cron: "0 1 * * 1"

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v5.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
          dot: true
          pr-number: ${{ github.event.pull_request.number }}

# Label configuration rules
labels:
  # Root-level changes
  root-level HTML:
    - changed-files:
        - '*.html'
  root-level styles:
    - changed-files:
        - '*.css'
  root-level scripts:
    - changed-files:
        - '*.js'

  # Subdirectory changes
  gallery images:
    - changed-files:
        - 'img/gallery/**'
  images:
    - changed-files:
        - 'img/**'

  # Detailed labels for specific changes
  feature addition:
    - changed-files:
        - '*.html'
        - '*.css'
        - '*.js'
        - 'img/**'
  bug fix:
    - changed-files:
        - '*.html'
        - '*.css'
        - '*.js'
        - 'img/**'
  hotfix:
    - changed-files:
        - '*.html'
        - '*.css'
        - '*.js'
        - 'img/**'

  # Documentation
  documentation:
    - changed-files:
        - 'README.md'
        - 'SECURITY.md'
