- name: Labeler
  uses: actions/labeler@v5.0.0
  with:
    # The GitHub token used to manage labels
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    # The path for the label configurations
    configuration-path: .github/labeler.yml
    # Whether or not to remove labels when matching files are reverted
    sync-labels: true
    # Whether or not to auto-include paths starting with dot (e.g. `.github`)
    dot: true
    # The pull request number(s)
    pr-number: ${{ github.event.pull_request.number }}

# Label configuration rules
labels:
  # Root-level changes
  root-level HTML:
    - changed-files:
        - '*.html'
  root-level styles:
    - changed-files:
        - '*.css'
  root-level scripts:
    - changed-files:
        - '*.js'

  # Subdirectory changes
  gallery images:
    - changed-files:
        - 'img/gallery/**'
  images:
    - changed-files:
        - 'img/**'

  # Detailed labels for specific changes
  feature addition:
    - changed-files:
        - '*.html'
        - '*.css'
        - '*.js'
        - 'img/**'
  bug fix:
    - changed-files:
        - '*.html'
        - '*.css'
        - '*.js'
        - 'img/**'
  hotfix:
    - changed-files:
        - '*.html'
        - '*.css'
        - '*.js'
        - 'img/**'

  # Documentation
  documentation:
    - changed-files:
        - 'README.md'
        - 'SECURITY.md'
