name: Dependency Vulnerability Scan

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.41.0_Linux-64bit.tar.gz | tar xz
          sudo mv trivy /usr/local/bin/

      - name: Run Trivy Dependency Scan
        run: trivy fs --severity HIGH,CRITICAL .
